# Generated by Django 4.2.1 on 2023-07-11 11:27

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_fooditem_glycemic_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, default=food.models.meal_default_image, null=True, upload_to=food.models.meal_image_upload_to),
        ),
    ]
