# Generated by Django 4.2.1 on 2023-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_fooditem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='glycemic_load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
